-- SQL: готовый вывод
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT * FROM users;', code_output=E'id | name | age\n1  | Анна | 25\n2  | Иван | 30' WHERE course_id='sql' AND position=2;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT name, age FROM users WHERE age > 18;', code_output=E'name | age\nАнна | 25\nИван | 30' WHERE course_id='sql' AND position=3;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT * FROM users ORDER BY age DESC;', code_output=E'id | name | age\n2  | Иван | 30\n1  | Анна | 25' WHERE course_id='sql' AND position=4;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT * FROM users ORDER BY age DESC LIMIT 1;', code_output=E'id | name | age\n2  | Иван | 30' WHERE course_id='sql' AND position=5;
UPDATE lessons SET code_lang='sql', code_sample=E'INSERT INTO people (id, name, age)\nVALUES (1, ''Пётр'', 28);\nSELECT * FROM people;', code_output=E'id | name | age\n1  | Пётр | 28' WHERE course_id='sql' AND position=6;
UPDATE lessons SET code_lang='sql', code_sample=E'UPDATE people SET age = 29 WHERE name = ''Пётр'';\nSELECT * FROM people WHERE name = ''Пётр'';', code_output=E'id | name | age\n1  | Пётр | 29' WHERE course_id='sql' AND position=7;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT COUNT(*) FROM users;\nSELECT AVG(age) FROM users;', code_output=E'COUNT(*)\n2\n\nAVG(age)\n27.5' WHERE course_id='sql' AND position=8;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT city, COUNT(*) FROM users GROUP BY city;', code_output=E'city   | COUNT(*)\nМосква | 1\nКазань | 1' WHERE course_id='sql' AND position=9;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT users.name, orders.product\nFROM users JOIN orders\nON users.id = orders.user_id;', code_output=E'name | product\nАнна | Книга\nИван | Ноутбук' WHERE course_id='sql' AND position=10;
UPDATE lessons SET code_lang='sql', code_sample=E'SELECT * FROM products WHERE price > 10000 ORDER BY price DESC;', code_output=E'id | name     | price | category\n1  | Телефон  | 30000 | Электроника' WHERE course_id='sql' AND position=12;

-- React: готовый вывод (превью результата)
UPDATE lessons SET code_lang='jsx', code_sample=E'function App() {\n  return <h1>Привет, React!</h1>;\n}', code_output=E'Привет, React!' WHERE course_id='react' AND position=1;
UPDATE lessons SET code_lang='jsx', code_sample=E'function App() {\n  const name = "Алекс";\n  return <h1>Привет, {name}</h1>;\n}', code_output=E'Привет, Алекс' WHERE course_id='react' AND position=2;
UPDATE lessons SET code_lang='jsx', code_sample=E'function Welcome() {\n  return <h2>Добро пожаловать!</h2>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Welcome />\n      <Welcome />\n    </div>\n  );\n}', code_output=E'Добро пожаловать!\nДобро пожаловать!' WHERE course_id='react' AND position=3;
UPDATE lessons SET code_lang='jsx', code_sample=E'function Card(props) {\n  return <h3>{props.title}</h3>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Card title="Первая карточка" />\n      <Card title="Вторая" />\n    </div>\n  );\n}', code_output=E'Первая карточка\nВторая' WHERE course_id='react' AND position=4;
UPDATE lessons SET code_lang='jsx', code_sample=E'import { useState } from "react";\n\nfunction App() {\n  const [count, setCount] = useState(0);\n  return (\n    <div>\n      <h1>{count}</h1>\n      <button onClick={() => setCount(count + 1)}>Плюс</button>\n    </div>\n  );\n}', code_output=E'0\n[Кнопка: Плюс]\n\n(после кликов счётчик растёт: 1, 2, 3...)' WHERE course_id='react' AND position=5;
UPDATE lessons SET code_lang='jsx', code_sample=E'const fruits = ["Яблоко", "Банан", "Вишня"];\n\nfunction App() {\n  return (\n    <ul>\n      {fruits.map(f => <li key={f}>{f}</li>)}\n    </ul>\n  );\n}', code_output=E'• Яблоко\n• Банан\n• Вишня' WHERE course_id='react' AND position=7;
UPDATE lessons SET code_lang='jsx', code_sample=E'function App() {\n  const [task, setTask] = useState("");\n  const [list, setList] = useState([]);\n  return (\n    <div>\n      <input value={task} onChange={e => setTask(e.target.value)} />\n      <button onClick={() => setList([...list, task])}>Добавить</button>\n      <p>Всего задач: {list.length}</p>\n    </div>\n  );\n}', code_output=E'[Поле ввода] [Кнопка: Добавить]\nВсего задач: 0\n\n(добавленные задачи появляются в списке)' WHERE course_id='react' AND position=12;